default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bootsy-demo_development

test: &test
  <<: *default
  database: bootsy-demo_test

production:
  adapter: postgresql
  encoding: unicode
  database: bootsy-demo_production
  pool: 5
  username: bootsy-demo
  password:
